_commit: v2.1.1
_src_path: gh:mopidy/cookiecutter-mopidy-ext
author_email: me@toino.pt
author_full_name: João Pereira
dist_name: mopidy-marceline
ext_name: marceline
github_username: ttoino
short_description: Mopidy extension for Foobar mechanics
