name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/mopidy-marceline/
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install node dependencies
        run: pnpm install --frozen-lockfile
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install python dependencies
        run: python -m pip install --upgrade pip tox
      - name: Build node package
        run: pnpm run build
      - name: Build python package
        run: python -m tox -e build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
