name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/project/mopidy-marceline/
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build javascript package
        run: pnpm run build
      - name: Build python package
        uses: hynek/build-and-inspect-python-package@v2
        id: build
      - name: Upload artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.build.outputs.artifact-name }}
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
