name: CI (Python)

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/ci-python.yml"
      - "mopidy_marceline/**"
      - "tests/**"
      - "pyproject.toml"

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Format
        run: python -m tox -e format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Lint
        run: python -m tox -e lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Typecheck
        run: python -m tox -e typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Test
        run: python -m tox -e test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - format
      - lint
      - typecheck
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Build
        run: python -m tox -e build
